apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: distributed-perf-testing
  labels:
    app: elasticsearch
spec:
  ports:
  - name: http
    port: 9200
    targetPort: http
    protocol: TCP
  - name: transport
    port: 9300
    targetPort: transport
    protocol: TCP
  clusterIP: None
  selector:
    app: elasticsearch
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: distributed-perf-testing
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch
  replicas: 3
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        ports:
        - name: http
          containerPort: 9200
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        resources:
          requests:
            cpu: 250m
            memory: 2Gi
        env:
        # not recommended for production use
        - name: node.store.allow_mmap
          value: "false"
        - name: discovery.seed_hosts
          value: "elasticsearch-0.elasticsearch.distributed-perf-testing.svc.cluster.local,elasticsearch-1.elasticsearch.distributed-perf-testing.svc.cluster.local,elasticsearch-2.elasticsearch.distributed-perf-testing.svc.cluster.local"
        - name: cluster.initial_master_nodes
          value: elasticsearch-0,elasticsearch-1,elasticsearch-2
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 4Gi
