apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: distributed-perf-testing
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
    targetPort: http
    protocol: TCP
  selector:
    app: kibana
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: distributed-perf-testing
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.7.0
        ports:
        - name: http
          containerPort: 5601
          protocol: TCP
        resources:
          requests:
            cpu: 125m
            memory: 128Mi

